version: '3'
services:
  injob-postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    container_name: injob-postgres-container
    ports:
      - 5432:5432
    networks:
      - injob-network

  injob-keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: ["-v", "start-dev", "--http-relative-path=/","--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: injob-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    container_name: injob-keycloak-container
    volumes:
      - ./keycloak/realms/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - injob-postgres
    networks:
      - injob-network

  injob-adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: injob-postgres
    command: [ "php", "-S", "[::]:8082", "-t", "/var/www/html"]
    container_name: injob-adminer-container
    ports:
      - 8082:8082
    networks:
      - injob-network
  
  injob-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: injobdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: azerty
    container_name: injobdb-container
    ports:
      - 5433:5432
    networks:
      - injob-network

  injob-back:
    image: injob-back:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://injob-db:5432/injobdb  # Corrected port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: azerty
      KEYCLOAK_AUTH_URL: http://injob-keycloak:8080/keycloak/auth/realms/in_job
      API_URL: http://injob-back:8081/back/api
      API_VERSION: 0.0.1
      SERVER_PORT: 8081
      KEYCLOAK_BASE_URL: http://injob-keycloak:8080
      REALM: in_job
    container_name: injobback-container
    ports:
      - 8081:8081
    depends_on:
      - injob-db
      - injob-keycloak
    networks:
      - injob-network  

volumes:
  postgres_data:

networks:
  injob-network:
