version: '3'
services:
  injob-postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    container_name: injob-postgres-container
    ports:
      - 5432:5432
  injob-keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: ["-v", "start-dev", "--http-relative-path=/auth","--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: injob-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    container_name: injob-keycloak-container
    # volumes:
    #   - ./keycloak/realms/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - injob-postgres
  injob-adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: injob-postgres
    command: [ "php", "-S", "[::]:8082", "-t", "/var/www/html"]
    container_name: injob-adminer-container
    ports:
      - 8082:8082
volumes:
  postgres_data: